global class KnowledgeSuggestionFilter {
	global KnowledgeSuggestionFilter() { }
	global void addArticleType(String articleType) { }
	global void addDataCategory(String dataCategoryGroupName, String dataCategoryName) { }
	global void addTopic(String topic) { }
	global void setChannel(String channelName) { }
	global void setDataCategories(Map<Object,Object> dataCategoryFilters) { }
	global void setLanguage(String localeCode) { }
	global void setPublishStatus(String publishStatus) { }
	global void setValidationStatus(String validationStatus) { }

}
