global class QuestionSuggestionFilter {
	global QuestionSuggestionFilter() { }
	global void addGroupId(String groupId) { }
	global void addNetworkId(String networkId) { }
	global void addUserId(String userId) { }
	global void setGroupIds(List<String> groupIds) { }
	global void setNetworkIds(List<String> networkIds) { }
	global void setTopicId(String topicId) { }
	global void setUserIds(List<String> userIds) { }

}