global class IdeaStandardController {
	global void addFields(List<String> fieldNames) { }
	global System.PageReference cancel() { }
	global System.PageReference delete() { }
	global System.PageReference edit() { }
	global List<IdeaComment> getCommentList() { }
	global String getId() { }
	global SObject getRecord() { }
	global System.PageReference save() { }
	global System.PageReference view() { }

}