global class KnowledgeArticleVersionStandardController {
	global KnowledgeArticleVersionStandardController(SObject sobject) { }
	global void addFields(List<String> fieldNames) { }
	global System.PageReference cancel() { }
	global String getId() { }
	global SObject getRecord() { }
	global String getSourceId() { }
	global void selectDataCategory(String categoryGroup, String category) { }
	global System.PageReference view() { }

}