global class ExtensionOutputRepresentation {
	global String domain;
	global String epn;
	global String name;
	global String product;
	global String status;
	global String type;
	global Integer version;
	global ExtensionOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}