global class PricingWaterFallResponseRepresentation {
	global List<ConnectApi.PricingAttributeNameValueTupleOutputRepresentation> customOutputs;
	global String discount;
	global String discountType;
	global String element;
	global Double listAmount;
	global ConnectApi.PricingWaterFallMetaDataResponseRepresentation metaData;
	global Double netAmount;
	global Integer stepNumber;
	global Double totalListAmount;
	global Double totalNetAmount;
	global String uuid;
	global PricingWaterFallResponseRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}