global class SelectOption {
	global SelectOption(String value, String label, Boolean disabled) { }
	global SelectOption(String value, String label) { }
	global Boolean getDisabled() { }
	global Boolean getEscapeItem() { }
	global String getLabel() { }
	global String getValue() { }
	global void setDisabled(Boolean disabled) { }
	global void setEscapeItem(Boolean disabled) { }
	global void setLabel(String label) { }
	global void setValue(String value) { }

}